services:
  db:
    image: postgres:16-alpine
    container_name: ueds_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ueds_user
      POSTGRES_PASSWORD: ueds_password
      POSTGRES_DB: ueds_db
    ports:
      - "5433:5432" # host:container  <-- changed
    volumes:
      - ueds_pgdata:/var/lib/postgresql/data

volumes:
  ueds_pgdata:
